const specialCharacters = [
  { from: "&Agrave;", to: "À" },
  { from: "&Aacute;", to: "Á" },
  { from: "&Acirc;", to: "Â" },
  { from: "&Atilde;", to: "Ã" },
  { from: "&Auml;", to: "Ä" },
  { from: "&Aring;", to: "Å" },
  { from: "&agrave;", to: "à" },
  { from: "&aacute;", to: "á" },
  { from: "&acirc;", to: "â" },
  { from: "&atilde;", to: "ã" },
  { from: "&auml;", to: "ä" },
  { from: "&aring;", to: "å" },
  { from: "&AElig;", to: "Æ" },
  { from: "&aelig;", to: "æ" },
  { from: "&szlig;", to: "ß" },
  { from: "&Ccedil;", to: "Ç" },
  { from: "&ccedil;", to: "ç" },
  { from: "&Egrave;", to: "È" },
  { from: "&Eacute;", to: "É" },
  { from: "&Ecirc;", to: "Ê" },
  { from: "&Euml;", to: "Ë" },
  { from: "&egrave;", to: "è" },
  { from: "&eacute;", to: "é" },
  { from: "&ecirc;", to: "ê" },
  { from: "&euml;", to: "ë" },
  { from: "&#131;", to: "ƒ" },
  { from: "&Igrave;", to: "Ì" },
  { from: "&Iacute;", to: "Í" },
  { from: "&Icirc;", to: "Î" },
  { from: "&Iuml;", to: "Ï" },
  { from: "&igrave;", to: "ì" },
  { from: "&iacute;", to: "í" },
  { from: "&icirc;", to: "î" },
  { from: "&iuml;", to: "ï" },
  { from: "&Ntilde;", to: "Ñ" },
  { from: "&ntilde;", to: "ñ" },
  { from: "&Ograve;", to: "Ò" },
  { from: "&Oacute;", to: "Ó" },
  { from: "&Ocirc;", to: "Ô" },
  { from: "&Otilde;", to: "Õ" },
  { from: "&Ouml;", to: "Ö" },
  { from: "&ograve;", to: "ò" },
  { from: "&oacute;", to: "ó" },
  { from: "&ocirc;", to: "ô" },
  { from: "&otilde;", to: "õ" },
  { from: "&ouml;", to: "ö" },
  { from: "&Oslash;", to: "Ø" },
  { from: "&oslash;", to: "ø" },
  { from: "&#140;", to: "Œ" },
  { from: "&#156;", to: "œ" },
  { from: "&#138;", to: "Š" },
  { from: "&#154;", to: "š" },
  { from: "&Ugrave;", to: "Ù" },
  { from: "&Uacute;", to: "Ú" },
  { from: "&Ucirc;", to: "Û" },
  { from: "&Uuml;", to: "Ü" },
  { from: "&ugrave;", to: "ù" },
  { from: "&uacute;", to: "ú" },
  { from: "&ucirc;", to: "û" },
  { from: "&uuml;", to: "ü" },
  { from: "&#181;", to: "µ" },
  { from: "&#215;", to: "×" },
  { from: "&Yacute;", to: "Ý" },
  { from: "&#159;", to: "Ÿ" },
  { from: "&yacute;", to: "ý" },
  { from: "&yuml;", to: "ÿ" },
  { from: "&#176;", to: "°" },
  { from: "&#134;", to: "†" },
  { from: "&#135;", to: "‡" },
  { from: "&lt;", to: "<" },
  { from: "&gt;", to: ">" },
  { from: "&#177;", to: "±" },
  { from: "&#171;", to: "«" },
  { from: "&#187;", to: "»" },
  { from: "&#191;", to: "¿" },
  { from: "&#161;", to: "¡" },
  { from: "&#183;", to: "·" },
  { from: "&#149;", to: "•" },
  { from: "&#153;", to: "™" },
  { from: "&copy;", to: "©" },
  { from: "&reg;", to: "®" },
  { from: "&#167;", to: "§" },
  { from: "&#182;", to: "¶" },
];

export function replaceSpecialCharacters(inputString) {
  specialCharacters.forEach((character) => {
    const regex = new RegExp(character.from, "g");
    inputString = inputString.replace(regex, character.to);
  });
  return inputString;
}
